// <auto-generated />
using System;
using HotelManagementApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManagementApi.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20251121070316_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingID"));

                    b.Property<int>("AdultCount")
                        .HasColumnType("int");

                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("BookingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Confirmed");

                    b.Property<DateTime?>("CancelDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ChildCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("BookingID");

                    b.HasIndex("BookingCode")
                        .IsUnique();

                    b.HasIndex("UserID");

                    b.ToTable("Booking", null, t =>
                        {
                            t.HasCheckConstraint("CK_Booking_Status", "BookingStatus IN ('Confirmed', 'Check-in', 'Check-out', 'Cancelled', 'No-show')");
                        });

                    b.HasData(
                        new
                        {
                            BookingID = 1,
                            AdultCount = 2,
                            BookingCode = "HTL25110001",
                            BookingStatus = "Confirmed",
                            ChildCount = 0,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4951),
                            DepositAmount = 500000m,
                            TotalAmount = 1600000m,
                            UserID = 5
                        },
                        new
                        {
                            BookingID = 2,
                            AdultCount = 1,
                            BookingCode = "HTL25110002",
                            BookingStatus = "Check-in",
                            ChildCount = 1,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4956),
                            DepositAmount = 2400000m,
                            TotalAmount = 2400000m,
                            UserID = 6
                        },
                        new
                        {
                            BookingID = 3,
                            AdultCount = 2,
                            BookingCode = "HTL25110003",
                            BookingStatus = "Cancelled",
                            ChildCount = 0,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4958),
                            DepositAmount = 0m,
                            TotalAmount = 3600000m,
                            UserID = 7
                        },
                        new
                        {
                            BookingID = 4,
                            AdultCount = 2,
                            BookingCode = "HTL25110004",
                            BookingStatus = "Confirmed",
                            ChildCount = 2,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4960),
                            DepositAmount = 1000000m,
                            TotalAmount = 5000000m,
                            UserID = 8
                        },
                        new
                        {
                            BookingID = 5,
                            AdultCount = 1,
                            BookingCode = "HTL25110005",
                            BookingStatus = "Check-out",
                            ChildCount = 0,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4962),
                            DepositAmount = 1200000m,
                            TotalAmount = 1200000m,
                            UserID = 9
                        },
                        new
                        {
                            BookingID = 6,
                            AdultCount = 3,
                            BookingCode = "HTL25110006",
                            BookingStatus = "Confirmed",
                            ChildCount = 1,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4963),
                            DepositAmount = 2000000m,
                            TotalAmount = 7500000m,
                            UserID = 10
                        },
                        new
                        {
                            BookingID = 7,
                            AdultCount = 2,
                            BookingCode = "HTL25110007",
                            BookingStatus = "No-show",
                            ChildCount = 0,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4964),
                            DepositAmount = 0m,
                            TotalAmount = 2400000m,
                            UserID = 11
                        },
                        new
                        {
                            BookingID = 8,
                            AdultCount = 2,
                            BookingCode = "HTL25110008",
                            BookingStatus = "Confirmed",
                            ChildCount = 0,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4966),
                            DepositAmount = 800000m,
                            TotalAmount = 1600000m,
                            UserID = 12
                        },
                        new
                        {
                            BookingID = 9,
                            AdultCount = 4,
                            BookingCode = "HTL25110009",
                            BookingStatus = "Confirmed",
                            ChildCount = 2,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4967),
                            DepositAmount = 3000000m,
                            TotalAmount = 10000000m,
                            UserID = 13
                        },
                        new
                        {
                            BookingID = 10,
                            AdultCount = 2,
                            BookingCode = "HTL25110010",
                            BookingStatus = "Check-in",
                            ChildCount = 0,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4974),
                            DepositAmount = 3600000m,
                            TotalAmount = 3600000m,
                            UserID = 14
                        },
                        new
                        {
                            BookingID = 11,
                            AdultCount = 1,
                            BookingCode = "HTL25110011",
                            BookingStatus = "Confirmed",
                            ChildCount = 0,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4985),
                            DepositAmount = 0m,
                            TotalAmount = 1200000m,
                            UserID = 15
                        },
                        new
                        {
                            BookingID = 12,
                            AdultCount = 2,
                            BookingCode = "HTL25110012",
                            BookingStatus = "Confirmed",
                            ChildCount = 1,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4986),
                            DepositAmount = 1500000m,
                            TotalAmount = 5000000m,
                            UserID = 16
                        },
                        new
                        {
                            BookingID = 13,
                            AdultCount = 3,
                            BookingCode = "HTL25110013",
                            BookingStatus = "Confirmed",
                            ChildCount = 0,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4988),
                            DepositAmount = 2000000m,
                            TotalAmount = 7500000m,
                            UserID = 17
                        },
                        new
                        {
                            BookingID = 14,
                            AdultCount = 2,
                            BookingCode = "HTL25110014",
                            BookingStatus = "Check-out",
                            ChildCount = 0,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4990),
                            DepositAmount = 2400000m,
                            TotalAmount = 2400000m,
                            UserID = 18
                        },
                        new
                        {
                            BookingID = 15,
                            AdultCount = 4,
                            BookingCode = "HTL25110015",
                            BookingStatus = "Confirmed",
                            ChildCount = 2,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4991),
                            DepositAmount = 4000000m,
                            TotalAmount = 12000000m,
                            UserID = 19
                        },
                        new
                        {
                            BookingID = 16,
                            AdultCount = 2,
                            BookingCode = "HTL25110016",
                            BookingStatus = "Confirmed",
                            ChildCount = 0,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4996),
                            DepositAmount = 0m,
                            TotalAmount = 1600000m,
                            UserID = 20
                        },
                        new
                        {
                            BookingID = 17,
                            AdultCount = 1,
                            BookingCode = "HTL25110017",
                            BookingStatus = "Confirmed",
                            ChildCount = 1,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4997),
                            DepositAmount = 1000000m,
                            TotalAmount = 3600000m,
                            UserID = 5
                        },
                        new
                        {
                            BookingID = 18,
                            AdultCount = 2,
                            BookingCode = "HTL25110018",
                            BookingStatus = "Check-in",
                            ChildCount = 0,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4998),
                            DepositAmount = 5000000m,
                            TotalAmount = 5000000m,
                            UserID = 6
                        },
                        new
                        {
                            BookingID = 19,
                            AdultCount = 3,
                            BookingCode = "HTL25110019",
                            BookingStatus = "Confirmed",
                            ChildCount = 1,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5000),
                            DepositAmount = 3000000m,
                            TotalAmount = 9000000m,
                            UserID = 7
                        },
                        new
                        {
                            BookingID = 20,
                            AdultCount = 2,
                            BookingCode = "HTL25110020",
                            BookingStatus = "Check-out",
                            ChildCount = 0,
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5001),
                            DepositAmount = 2400000m,
                            TotalAmount = 2400000m,
                            UserID = 8
                        });
                });

            modelBuilder.Entity("BookingDetail", b =>
                {
                    b.Property<int>("BookingDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingDetailID"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.Property<int>("RoomTypeID")
                        .HasColumnType("int");

                    b.HasKey("BookingDetailID");

                    b.HasIndex("BookingID");

                    b.HasIndex("RoomTypeID");

                    b.HasIndex("RoomID", "CheckInDate", "CheckOutDate")
                        .IsUnique()
                        .HasDatabaseName("UX_BookingDetail_Room_Period");

                    b.ToTable("BookingDetails", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookingDetail_DateRange", "CheckOutDate > CheckInDate");

                            t.HasCheckConstraint("CK_BookingDetail_Price", "PricePerNight > 0");
                        });

                    b.HasData(
                        new
                        {
                            BookingDetailID = 1,
                            BookingID = 1,
                            CheckInDate = new DateTime(2025, 12, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 12, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 800000m,
                            RoomID = 1,
                            RoomTypeID = 1
                        },
                        new
                        {
                            BookingDetailID = 2,
                            BookingID = 2,
                            CheckInDate = new DateTime(2025, 11, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            CheckOutDate = new DateTime(2025, 11, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            PricePerNight = 800000m,
                            RoomID = 2,
                            RoomTypeID = 1
                        },
                        new
                        {
                            BookingDetailID = 3,
                            BookingID = 3,
                            CheckInDate = new DateTime(2025, 1, 5, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 1, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 1200000m,
                            RoomID = 3,
                            RoomTypeID = 2
                        },
                        new
                        {
                            BookingDetailID = 4,
                            BookingID = 4,
                            CheckInDate = new DateTime(2025, 3, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 3, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 1200000m,
                            RoomID = 4,
                            RoomTypeID = 2
                        },
                        new
                        {
                            BookingDetailID = 5,
                            BookingID = 5,
                            CheckInDate = new DateTime(2025, 3, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 3, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 2500000m,
                            RoomID = 5,
                            RoomTypeID = 3
                        },
                        new
                        {
                            BookingDetailID = 6,
                            BookingID = 6,
                            CheckInDate = new DateTime(2025, 4, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 4, 22, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 2500000m,
                            RoomID = 6,
                            RoomTypeID = 3
                        },
                        new
                        {
                            BookingDetailID = 7,
                            BookingID = 7,
                            CheckInDate = new DateTime(2025, 5, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 5, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 1800000m,
                            RoomID = 7,
                            RoomTypeID = 4
                        },
                        new
                        {
                            BookingDetailID = 8,
                            BookingID = 8,
                            CheckInDate = new DateTime(2025, 5, 28, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 5, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 1800000m,
                            RoomID = 8,
                            RoomTypeID = 4
                        },
                        new
                        {
                            BookingDetailID = 9,
                            BookingID = 9,
                            CheckInDate = new DateTime(2025, 5, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 5, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 800000m,
                            RoomID = 9,
                            RoomTypeID = 1
                        },
                        new
                        {
                            BookingDetailID = 10,
                            BookingID = 10,
                            CheckInDate = new DateTime(2025, 6, 6, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 6, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 800000m,
                            RoomID = 10,
                            RoomTypeID = 1
                        },
                        new
                        {
                            BookingDetailID = 11,
                            BookingID = 11,
                            CheckInDate = new DateTime(2025, 6, 9, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 6, 11, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 1200000m,
                            RoomID = 11,
                            RoomTypeID = 2
                        },
                        new
                        {
                            BookingDetailID = 12,
                            BookingID = 12,
                            CheckInDate = new DateTime(2025, 7, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 7, 14, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 1200000m,
                            RoomID = 12,
                            RoomTypeID = 2
                        },
                        new
                        {
                            BookingDetailID = 13,
                            BookingID = 13,
                            CheckInDate = new DateTime(2025, 8, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 8, 17, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 2500000m,
                            RoomID = 13,
                            RoomTypeID = 3
                        },
                        new
                        {
                            BookingDetailID = 14,
                            BookingID = 14,
                            CheckInDate = new DateTime(2025, 8, 18, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 8, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 2500000m,
                            RoomID = 14,
                            RoomTypeID = 3
                        },
                        new
                        {
                            BookingDetailID = 15,
                            BookingID = 15,
                            CheckInDate = new DateTime(2025, 9, 21, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 9, 24, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 1800000m,
                            RoomID = 15,
                            RoomTypeID = 4
                        },
                        new
                        {
                            BookingDetailID = 16,
                            BookingID = 16,
                            CheckInDate = new DateTime(2025, 9, 25, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 9, 27, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 1800000m,
                            RoomID = 16,
                            RoomTypeID = 4
                        },
                        new
                        {
                            BookingDetailID = 17,
                            BookingID = 17,
                            CheckInDate = new DateTime(2025, 10, 28, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 10, 30, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 800000m,
                            RoomID = 17,
                            RoomTypeID = 1
                        },
                        new
                        {
                            BookingDetailID = 18,
                            BookingID = 18,
                            CheckInDate = new DateTime(2025, 11, 1, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 11, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 1200000m,
                            RoomID = 18,
                            RoomTypeID = 2
                        },
                        new
                        {
                            BookingDetailID = 19,
                            BookingID = 19,
                            CheckInDate = new DateTime(2025, 11, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 11, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 2500000m,
                            RoomID = 19,
                            RoomTypeID = 3
                        },
                        new
                        {
                            BookingDetailID = 20,
                            BookingID = 20,
                            CheckInDate = new DateTime(2025, 12, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2025, 12, 10, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            PricePerNight = 1800000m,
                            RoomID = 20,
                            RoomTypeID = 4
                        });
                });

            modelBuilder.Entity("HotelManagementApi.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Other");

                    b.Property<string>("IdCard")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Customer");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdCard")
                        .IsUnique()
                        .HasFilter("[IdCard] IS NOT NULL");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Gender", "Gender IN ('Male', 'Female', 'Other')");

                            t.HasCheckConstraint("CK_Users_Role", "UserRole IN ('Admin', 'Receptionist', 'Customer')");
                        });

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Address = "123 Đường Lê Lợi, Quận 1, TP.HCM",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4459),
                            DateOfBirth = new DateTime(1985, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@hotel.com",
                            FirstName = "Nguyễn",
                            Gender = "Male",
                            IdCard = "00123456789",
                            LastName = "Văn Quý",
                            Nationality = "VietNam",
                            Notes = "Quản trị viên hệ thống - Chủ khách sạn",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0901000001",
                            UserRole = "Admin"
                        },
                        new
                        {
                            UserID = 2,
                            Address = "456 Hai Bà Trưng, Q3",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4482),
                            DateOfBirth = new DateTime(1996, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "lan@hotel.com",
                            FirstName = "Trần",
                            Gender = "Female",
                            IdCard = "00123456790",
                            LastName = "Thị Lan",
                            Nationality = "VietNam",
                            Notes = "Lễ tân ca sáng",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0901000002",
                            UserRole = "Receptionist"
                        },
                        new
                        {
                            UserID = 3,
                            Address = "789 Nguyễn Huệ, Q1",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4485),
                            DateOfBirth = new DateTime(1994, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hung@hotel.com",
                            FirstName = "Lê",
                            Gender = "Male",
                            IdCard = "00123456791",
                            LastName = "Văn Hùng",
                            Nationality = "VietNam",
                            Notes = "Lễ tân ca tối",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0901000003",
                            UserRole = "Receptionist"
                        },
                        new
                        {
                            UserID = 4,
                            Address = "321 Bùi Viện, Q1",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4487),
                            DateOfBirth = new DateTime(1998, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mai@hotel.com",
                            FirstName = "Phạm",
                            Gender = "Female",
                            IdCard = "00123456792",
                            LastName = "Thị Mai",
                            Nationality = "VietNam",
                            Notes = "Lễ tân ca đêm",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0901000004",
                            UserRole = "Receptionist"
                        },
                        new
                        {
                            UserID = 5,
                            Address = "Hà Nội",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4489),
                            DateOfBirth = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "an@gmail.com",
                            FirstName = "Nguyễn",
                            Gender = "Male",
                            IdCard = "00123456793",
                            LastName = "Văn An",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000005",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 6,
                            Address = "Đà Nẵng",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4491),
                            DateOfBirth = new DateTime(1992, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "binh@gmail.com",
                            FirstName = "Trần",
                            Gender = "Female",
                            IdCard = "00123456794",
                            LastName = "Thị Bình",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000006",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 7,
                            Address = "Nha Trang",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4493),
                            DateOfBirth = new DateTime(1988, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "cuong@gmail.com",
                            FirstName = "Lê",
                            Gender = "Male",
                            IdCard = "00123456795",
                            LastName = "Văn Cường",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000007",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 8,
                            Address = "Phú Quốc",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4495),
                            DateOfBirth = new DateTime(1995, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dung@gmail.com",
                            FirstName = "Phạm",
                            Gender = "Female",
                            IdCard = "00123456796",
                            LastName = "Thị Dung",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000008",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 9,
                            Address = "Cần Thơ",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4496),
                            DateOfBirth = new DateTime(1993, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "em@gmail.com",
                            FirstName = "Hoàng",
                            Gender = "Male",
                            IdCard = "00123456797",
                            LastName = "Văn Em",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000009",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 10,
                            Address = "Hải Phòng",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4498),
                            DateOfBirth = new DateTime(1991, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "phuong@gmail.com",
                            FirstName = "Vũ",
                            Gender = "Female",
                            IdCard = "00123456798",
                            LastName = "Thị Phượng",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000010",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 11,
                            Address = "Vũng Tàu",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4500),
                            DateOfBirth = new DateTime(1989, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "giang@gmail.com",
                            FirstName = "Đặng",
                            Gender = "Male",
                            IdCard = "00123456799",
                            LastName = "Văn Giang",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000011",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 12,
                            Address = "Đà Lạt",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4502),
                            DateOfBirth = new DateTime(1997, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hanh@gmail.com",
                            FirstName = "Bùi",
                            Gender = "Female",
                            IdCard = "00123456100",
                            LastName = "Thị Hạnh",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000012",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 13,
                            Address = "Huế",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4504),
                            DateOfBirth = new DateTime(1994, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "inh@gmail.com",
                            FirstName = "Đỗ",
                            Gender = "Male",
                            IdCard = "00123456101",
                            LastName = "Văn Inh",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000013",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 14,
                            Address = "Quảng Ninh",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4505),
                            DateOfBirth = new DateTime(1996, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kieu@gmail.com",
                            FirstName = "Ngô",
                            Gender = "Female",
                            IdCard = "00123456102",
                            LastName = "Thị Kiều",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000014",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 15,
                            Address = "Sapa",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4508),
                            DateOfBirth = new DateTime(1990, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "long@gmail.com",
                            FirstName = "Hà",
                            Gender = "Male",
                            IdCard = "00123456103",
                            LastName = "Văn Long",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000015",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 16,
                            Address = "Hội An",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4510),
                            DateOfBirth = new DateTime(1992, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "minh@gmail.com",
                            FirstName = "Lý",
                            Gender = "Female",
                            IdCard = "00123456104",
                            LastName = "Thị Minh",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000016",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 17,
                            Address = "Ninh Bình",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4512),
                            DateOfBirth = new DateTime(1987, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nam@gmail.com",
                            FirstName = "Mai",
                            Gender = "Male",
                            IdCard = "00123456105",
                            LastName = "Văn Nam",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000017",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 18,
                            Address = "Phan Thiết",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4513),
                            DateOfBirth = new DateTime(1999, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "oanh@gmail.com",
                            FirstName = "Tô",
                            Gender = "Female",
                            IdCard = "00123456106",
                            LastName = "Thị Oanh",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000018",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 19,
                            Address = "Quy Nhơn",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4515),
                            DateOfBirth = new DateTime(1993, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "phong@gmail.com",
                            FirstName = "Dương",
                            Gender = "Male",
                            IdCard = "00123456107",
                            LastName = "Văn Phong",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000019",
                            UserRole = "Customer"
                        },
                        new
                        {
                            UserID = 20,
                            Address = "Cà Mau",
                            CreatedDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(4517),
                            DateOfBirth = new DateTime(1995, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "quyen@gmail.com",
                            FirstName = "Chu",
                            Gender = "Female",
                            IdCard = "00123456108",
                            LastName = "Thị Quyên",
                            Nationality = "VietNam",
                            PasswordHash = "$2a$11$wKO6/iSu6D3riZ/.CmqIx.cpVx511YlntA8Da.6BadcN8pv/dyrKS",
                            Phone = "0911000020",
                            UserRole = "Customer"
                        });
                });

            modelBuilder.Entity("Invoice", b =>
                {
                    b.Property<int>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceID"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Complete");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRoomCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalServiceCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VATPercent")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("InvoiceID");

                    b.HasIndex("BookingID")
                        .IsUnique();

                    b.HasIndex("InvoiceCode")
                        .IsUnique();

                    b.ToTable("Invoice", null, t =>
                        {
                            t.HasCheckConstraint("CK_Invoice_PaymentStatus", "PaymentStatus IN ('Complete')");
                        });

                    b.HasData(
                        new
                        {
                            InvoiceID = 1,
                            BookingID = 1,
                            InvoiceCode = "INV25110001",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5147),
                            PaidAmount = 500000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 1600000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 2,
                            BookingID = 2,
                            InvoiceCode = "INV25110002",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5151),
                            PaidAmount = 2400000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 2400000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 3,
                            BookingID = 3,
                            InvoiceCode = "INV25110003",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5152),
                            PaidAmount = 0m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 3600000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 4,
                            BookingID = 4,
                            InvoiceCode = "INV25110004",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5154),
                            PaidAmount = 1000000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 5000000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 5,
                            BookingID = 5,
                            InvoiceCode = "INV25110005",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5155),
                            PaidAmount = 1200000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 1200000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 6,
                            BookingID = 6,
                            InvoiceCode = "INV25110006",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5157),
                            PaidAmount = 2000000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 7500000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 7,
                            BookingID = 7,
                            InvoiceCode = "INV25110007",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5158),
                            PaidAmount = 0m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 2400000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 8,
                            BookingID = 8,
                            InvoiceCode = "INV25110008",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5159),
                            PaidAmount = 800000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 1600000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 9,
                            BookingID = 9,
                            InvoiceCode = "INV25110009",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5161),
                            PaidAmount = 3000000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 10000000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 10,
                            BookingID = 10,
                            InvoiceCode = "INV25110010",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5162),
                            PaidAmount = 3600000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 3600000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 11,
                            BookingID = 11,
                            InvoiceCode = "INV25110011",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5163),
                            PaidAmount = 0m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 1200000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 12,
                            BookingID = 12,
                            InvoiceCode = "INV25110012",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5164),
                            PaidAmount = 1500000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 5000000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 13,
                            BookingID = 13,
                            InvoiceCode = "INV25110013",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5165),
                            PaidAmount = 2000000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 7500000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 14,
                            BookingID = 14,
                            InvoiceCode = "INV25110014",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5167),
                            PaidAmount = 2400000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 2400000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 15,
                            BookingID = 15,
                            InvoiceCode = "INV25110015",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5168),
                            PaidAmount = 4000000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 12000000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 16,
                            BookingID = 16,
                            InvoiceCode = "INV25110016",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5169),
                            PaidAmount = 0m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 1600000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 17,
                            BookingID = 17,
                            InvoiceCode = "INV25110017",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5171),
                            PaidAmount = 1000000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 3600000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 18,
                            BookingID = 18,
                            InvoiceCode = "INV25110018",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5172),
                            PaidAmount = 5000000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 5000000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 19,
                            BookingID = 19,
                            InvoiceCode = "INV25110019",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5174),
                            PaidAmount = 3000000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 9000000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        },
                        new
                        {
                            InvoiceID = 20,
                            BookingID = 20,
                            InvoiceCode = "INV25110020",
                            IssueDate = new DateTime(2025, 11, 21, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5175),
                            PaidAmount = 2400000m,
                            PaymentStatus = "Complete",
                            TotalDiscount = 0m,
                            TotalRoomCharge = 2400000m,
                            TotalServiceCharge = 0m,
                            VATPercent = 10m
                        });
                });

            modelBuilder.Entity("Room", b =>
                {
                    b.Property<int>("RoomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomID"));

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RoomTypeID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Available");

                    b.HasKey("RoomID");

                    b.HasIndex("RoomNumber")
                        .IsUnique();

                    b.HasIndex("RoomTypeID");

                    b.HasIndex("Status", "RoomTypeID")
                        .HasDatabaseName("IX_Room_Status_Type");

                    b.ToTable("Room", null, t =>
                        {
                            t.HasCheckConstraint("CK_Room_Status", "Status IN ('Available', 'Booked', 'Occupied', 'Maintenance')");
                        });

                    b.HasData(
                        new
                        {
                            RoomID = 1,
                            Floor = 1,
                            IsActive = true,
                            RoomNumber = "101",
                            RoomTypeID = 1,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 2,
                            Floor = 1,
                            IsActive = true,
                            RoomNumber = "102",
                            RoomTypeID = 1,
                            Status = "Occupied"
                        },
                        new
                        {
                            RoomID = 3,
                            Floor = 1,
                            IsActive = true,
                            RoomNumber = "103",
                            RoomTypeID = 2,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 4,
                            Floor = 1,
                            IsActive = true,
                            RoomNumber = "104",
                            RoomTypeID = 2,
                            Status = "Occupied"
                        },
                        new
                        {
                            RoomID = 5,
                            Floor = 2,
                            IsActive = true,
                            RoomNumber = "201",
                            RoomTypeID = 3,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 6,
                            Floor = 2,
                            IsActive = true,
                            RoomNumber = "202",
                            RoomTypeID = 3,
                            Status = "Occupied"
                        },
                        new
                        {
                            RoomID = 7,
                            Floor = 2,
                            IsActive = true,
                            RoomNumber = "203",
                            RoomTypeID = 4,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 8,
                            Floor = 2,
                            IsActive = true,
                            RoomNumber = "204",
                            RoomTypeID = 4,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 9,
                            Floor = 3,
                            IsActive = true,
                            RoomNumber = "301",
                            RoomTypeID = 1,
                            Status = "Maintenance"
                        },
                        new
                        {
                            RoomID = 10,
                            Floor = 3,
                            IsActive = true,
                            RoomNumber = "302",
                            RoomTypeID = 1,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 11,
                            Floor = 3,
                            IsActive = true,
                            RoomNumber = "303",
                            RoomTypeID = 2,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 12,
                            Floor = 3,
                            IsActive = true,
                            RoomNumber = "304",
                            RoomTypeID = 2,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 13,
                            Floor = 4,
                            IsActive = true,
                            RoomNumber = "401",
                            RoomTypeID = 3,
                            Status = "Occupied"
                        },
                        new
                        {
                            RoomID = 14,
                            Floor = 4,
                            IsActive = true,
                            RoomNumber = "402",
                            RoomTypeID = 3,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 15,
                            Floor = 4,
                            IsActive = true,
                            RoomNumber = "403",
                            RoomTypeID = 4,
                            Status = "Occupied"
                        },
                        new
                        {
                            RoomID = 16,
                            Floor = 4,
                            IsActive = true,
                            RoomNumber = "404",
                            RoomTypeID = 4,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 17,
                            Floor = 5,
                            IsActive = true,
                            RoomNumber = "501",
                            RoomTypeID = 1,
                            Status = "Occupied"
                        },
                        new
                        {
                            RoomID = 18,
                            Floor = 5,
                            IsActive = true,
                            RoomNumber = "502",
                            RoomTypeID = 2,
                            Status = "Available"
                        },
                        new
                        {
                            RoomID = 19,
                            Floor = 5,
                            IsActive = true,
                            RoomNumber = "503",
                            RoomTypeID = 3,
                            Status = "Maintenance"
                        },
                        new
                        {
                            RoomID = 20,
                            Floor = 5,
                            IsActive = true,
                            RoomNumber = "504",
                            RoomTypeID = 4,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("RoomStatusLog", b =>
                {
                    b.Property<int>("LogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogID"));

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.HasKey("LogID");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("RoomID");

                    b.ToTable("RoomStatusLogs", (string)null);

                    b.HasData(
                        new
                        {
                            LogID = 1,
                            ChangedBy = 2,
                            ChangedDate = new DateTime(2025, 11, 16, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5212),
                            NewStatus = "Booked",
                            OldStatus = "Available",
                            Reason = "Đặt phòng HTL25110001",
                            RoomID = 1
                        },
                        new
                        {
                            LogID = 2,
                            ChangedBy = 3,
                            ChangedDate = new DateTime(2025, 11, 20, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5214),
                            NewStatus = "Occupied",
                            OldStatus = "Available",
                            Reason = "Check-in khách walk-in",
                            RoomID = 2
                        },
                        new
                        {
                            LogID = 3,
                            ChangedBy = 4,
                            ChangedDate = new DateTime(2025, 11, 18, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5216),
                            NewStatus = "Booked",
                            OldStatus = "Available",
                            Reason = "Đặt phòng HTL25110003",
                            RoomID = 3
                        },
                        new
                        {
                            LogID = 4,
                            ChangedBy = 2,
                            ChangedDate = new DateTime(2025, 11, 19, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5218),
                            NewStatus = "Occupied",
                            OldStatus = "Booked",
                            Reason = "Check-in sớm",
                            RoomID = 4
                        },
                        new
                        {
                            LogID = 5,
                            ChangedBy = 3,
                            ChangedDate = new DateTime(2025, 11, 17, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5219),
                            NewStatus = "Booked",
                            OldStatus = "Available",
                            Reason = "Đặt phòng HTL25110005",
                            RoomID = 5
                        },
                        new
                        {
                            LogID = 6,
                            ChangedBy = 4,
                            ChangedDate = new DateTime(2025, 11, 15, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5221),
                            NewStatus = "Occupied",
                            OldStatus = "Booked",
                            Reason = "Check-in",
                            RoomID = 6
                        },
                        new
                        {
                            LogID = 7,
                            ChangedBy = 2,
                            ChangedDate = new DateTime(2025, 11, 14, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5223),
                            NewStatus = "Available",
                            OldStatus = "Occupied",
                            Reason = "Check-out",
                            RoomID = 7
                        },
                        new
                        {
                            LogID = 8,
                            ChangedBy = 3,
                            ChangedDate = new DateTime(2025, 11, 13, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5225),
                            NewStatus = "Booked",
                            OldStatus = "Available",
                            Reason = "Đặt phòng HTL25110008",
                            RoomID = 8
                        },
                        new
                        {
                            LogID = 9,
                            ChangedBy = 1,
                            ChangedDate = new DateTime(2025, 11, 11, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5227),
                            NewStatus = "Available",
                            OldStatus = "Maintenance",
                            Reason = "Sửa chữa xong",
                            RoomID = 9
                        },
                        new
                        {
                            LogID = 10,
                            ChangedBy = 4,
                            ChangedDate = new DateTime(2025, 11, 12, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5230),
                            NewStatus = "Booked",
                            OldStatus = "Available",
                            Reason = "Đặt phòng",
                            RoomID = 10
                        },
                        new
                        {
                            LogID = 11,
                            ChangedBy = 2,
                            ChangedDate = new DateTime(2025, 11, 10, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5231),
                            NewStatus = "Occupied",
                            OldStatus = "Booked",
                            Reason = "Check-in",
                            RoomID = 11
                        },
                        new
                        {
                            LogID = 12,
                            ChangedBy = 3,
                            ChangedDate = new DateTime(2025, 11, 9, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5233),
                            NewStatus = "Available",
                            OldStatus = "Occupied",
                            Reason = "Check-out",
                            RoomID = 12
                        },
                        new
                        {
                            LogID = 13,
                            ChangedBy = 4,
                            ChangedDate = new DateTime(2025, 11, 8, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5235),
                            NewStatus = "Booked",
                            OldStatus = "Available",
                            Reason = "Đặt phòng",
                            RoomID = 13
                        },
                        new
                        {
                            LogID = 14,
                            ChangedBy = 2,
                            ChangedDate = new DateTime(2025, 11, 7, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5237),
                            NewStatus = "Occupied",
                            OldStatus = "Booked",
                            Reason = "Check-in",
                            RoomID = 14
                        },
                        new
                        {
                            LogID = 15,
                            ChangedBy = 3,
                            ChangedDate = new DateTime(2025, 11, 6, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5238),
                            NewStatus = "Available",
                            OldStatus = "Occupied",
                            Reason = "Check-out",
                            RoomID = 15
                        },
                        new
                        {
                            LogID = 16,
                            ChangedBy = 4,
                            ChangedDate = new DateTime(2025, 11, 5, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5240),
                            NewStatus = "Booked",
                            OldStatus = "Available",
                            Reason = "Đặt phòng",
                            RoomID = 16
                        },
                        new
                        {
                            LogID = 17,
                            ChangedBy = 2,
                            ChangedDate = new DateTime(2025, 11, 4, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5242),
                            NewStatus = "Occupied",
                            OldStatus = "Booked",
                            Reason = "Check-in",
                            RoomID = 17
                        },
                        new
                        {
                            LogID = 18,
                            ChangedBy = 3,
                            ChangedDate = new DateTime(2025, 11, 3, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5243),
                            NewStatus = "Available",
                            OldStatus = "Occupied",
                            Reason = "Check-out",
                            RoomID = 18
                        },
                        new
                        {
                            LogID = 19,
                            ChangedBy = 4,
                            ChangedDate = new DateTime(2025, 11, 2, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5245),
                            NewStatus = "Booked",
                            OldStatus = "Available",
                            Reason = "Đặt phòng",
                            RoomID = 19
                        },
                        new
                        {
                            LogID = 20,
                            ChangedBy = 2,
                            ChangedDate = new DateTime(2025, 11, 1, 14, 3, 14, 467, DateTimeKind.Local).AddTicks(5246),
                            NewStatus = "Occupied",
                            OldStatus = "Booked",
                            Reason = "Check-in",
                            RoomID = 20
                        });
                });

            modelBuilder.Entity("RoomType", b =>
                {
                    b.Property<int>("RoomTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomTypeID"));

                    b.Property<decimal>("AreaSqm")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BedType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoomTypeID");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("RoomTypes", (string)null);

                    b.HasData(
                        new
                        {
                            RoomTypeID = 1,
                            AreaSqm = 25.00m,
                            BasePrice = 800000m,
                            BedType = "Double",
                            Capacity = 2,
                            Description = "Phòng tiêu chuẩn",
                            IsActive = true,
                            TypeName = "Standard"
                        },
                        new
                        {
                            RoomTypeID = 2,
                            AreaSqm = 35.00m,
                            BasePrice = 1200000m,
                            BedType = "King",
                            Capacity = 2,
                            Description = "Phòng cao cấp",
                            IsActive = true,
                            TypeName = "Deluxe"
                        },
                        new
                        {
                            RoomTypeID = 3,
                            AreaSqm = 60.00m,
                            BasePrice = 2500000m,
                            BedType = "2 Queen",
                            Capacity = 4,
                            Description = "Phòng suite",
                            IsActive = true,
                            TypeName = "Suite"
                        },
                        new
                        {
                            RoomTypeID = 4,
                            AreaSqm = 45.00m,
                            BasePrice = 1800000m,
                            BedType = "2 Double",
                            Capacity = 4,
                            Description = "Phòng gia đình",
                            IsActive = true,
                            TypeName = "Family"
                        });
                });

            modelBuilder.Entity("Booking", b =>
                {
                    b.HasOne("HotelManagementApi.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BookingDetail", b =>
                {
                    b.HasOne("Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Room", "Room")
                        .WithMany("BookingDetails")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoomType", "RoomType")
                        .WithMany()
                        .HasForeignKey("RoomTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Room");

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("Invoice", b =>
                {
                    b.HasOne("Booking", "Booking")
                        .WithOne("Invoice")
                        .HasForeignKey("Invoice", "BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Room", b =>
                {
                    b.HasOne("RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomType");
                });

            modelBuilder.Entity("RoomStatusLog", b =>
                {
                    b.HasOne("HotelManagementApi.Models.User", "ChangedByUser")
                        .WithMany("RoomStatusLogs")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Room", "Room")
                        .WithMany("StatusLogs")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Booking", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("HotelManagementApi.Models.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("RoomStatusLogs");
                });

            modelBuilder.Entity("Room", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("StatusLogs");
                });

            modelBuilder.Entity("RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
